name: bloat-guard
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run repo-bloat-guard (Markdown report + enforce)
        env:
          BG_FAIL_ABS: "1572864"
          BG_FAIL_REL: "12"
          BG_EXCLUDE: "**/*.map,**/*.lock,**/node_modules/**"
          BG_BUDGETS_FILE: ".bloatbudgets.json"
        shell: bash
        run: |
          set -e
          BASE_SHA="${{ github.event.pull_request.base.sha || 'origin/main' }}"
          set -o pipefail
          python bloat_guard.py --ref-base "$BASE_SHA" --fail-on "+1.5MB or +12%" --markdown | tee bloat_report.md
          STATUS=${PIPESTATUS[0]}
          echo "status=$STATUS" >> $GITHUB_OUTPUT
          exit $STATUS
      - name: Upload bloat report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bloat-report
          path: bloat_report.md
      - name: Comment bloat report on PR
        if: ${{ github.event.pull_request.number != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        shell: bash
        run: |
          body=$(jq -Rs . < bloat_report.md)
          curl -s -X POST \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments" \
            -d "{\"body\": ${body}}"